<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllOrdered(){
		return $this->getEntityManager()
			->createQuery(
				'Select p
				From AppBundle:Project p
				Order By p.orderId'
			)
			->getResult()
		;
	}
}
