twig:
    globals:
        web_firstName: '%web_firstName%'
        web_lastName: '%web_lastName%'
        web_company: '%web_company%'
        web_copyright: '%web_copyright%'
        web_city: '%web_city%'
        web_phone: '%web_phone%'
        web_email: '%web_email%'

        photos_directory: '%photos_directory%'
        web_photos_directory: '%web_photos_directory%'
        thumbs_directory: '%thumbs_directory%'
        web_thumbs_directory: '%web_thumbs_directory%'
